services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment: 
      MYSQL_ROOT_PASSWORD: tierraviva123
      MYSQL_DATABASE: tierraviva_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  ## backend:
    ##build:
      ##context: ../backend
      ##dockerfile: Dockerfile
    ##container_name: tierraviva_backend
    ## ports:
      ##- "8080:8080"
    ##depends_on:
      ##- mysql
    ##environment:
      ##SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/tierraviva_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      ##SPRING_DATASOURCE_USERNAME: root
      ##SPRING_DATASOURCE_PASSWORD: tierraviva123

volumes:
  mysql_data:
